[versions]
# Main
composeColorPickerAndroid = "0.7.0"
ical4j = "4.2.3"
junit = "4.13.2"
kotlin = "2.3.0"
coroutines = "1.10.2"
agp = "9.0.0"
core = "1.17.0"
ksp = "2.3.3"

# Benchmark / performance
okhttp = "5.3.2"
pdfboxAndroid = "2.0.27.0"
profileinstaller = "1.4.1"

# Compose
compose = "2026.01.01"

accompanist = "0.37.3"
coil = "2.7.0"
navigation = "2.9.7"
material3 = "1.4.0"
materialNavigation = "1.10.2"
runner = "1.7.0"
runtime-livedata = "1.10.2"

# App components
activity = "1.12.3"
activity-compose = "1.12.3"
paging = "3.4.0"
paging-compose = "3.4.0"

appcompat = "1.7.1"
fragment = "1.8.9"
lifecycle = "2.10.0"
material = "1.13.0"
preference = "1.2.1"
security = "1.1.0"
swiperefreshlayout = "1.2.0"
webkit = "1.15.0"
datastore = "1.2.0"
startup = "1.2.0"
splashscreen = "1.2.0"
documentfile = "1.1.0"

# Integration
browser = "1.9.0"
googleServices = "4.4.4"
inAppUpdate = "2.1.0"

# Firebase
firebase = "34.8.0"
firebaseGradle = "3.0.6"

# Network
retrofit = "3.0.0"
jsoup = "1.22.1"
okhttp3 = "5.3.2"

# Room DB
room = "2.8.4"

# DI
hilt = "2.59"
hilt-nav = "1.3.0"

# Other
joda = "2.14.0"
reorderable = "3.0.0"

# Worker
work = "2.11.1"
work-hilt = "1.3.0"

[libraries]
# Main
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-rules = { module = "androidx.test:rules", version.ref = "runner" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
compose-color-picker-android = { module = "com.godaddy.android.colorpicker:compose-color-picker-android", version.ref = "composeColorPickerAndroid" }
ical4j = { module = "org.mnode.ical4j:ical4j", version.ref = "ical4j" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Benchmark / performance
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-materialNavigation = { module = "androidx.compose.material:material-navigation", version.ref = "materialNavigation" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtime-livedata" }


accompanist-permission = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }

# Components
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-pagingCommon = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-security = { module = "androidx.security:security-crypto", version.ref = "security" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# Integration
integration-browser = { module = "androidx.browser:browser", version.ref = "browser" }
integration-inAppUpdate = { module = "com.google.android.play:app-update-ktx", version.ref = "inAppUpdate" }

# UI
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfboxAndroid" }
ui-material = { module = "com.google.android.material:material", version.ref = "material" }
ui-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseGradle" }

# Network
network-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
network-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
network-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
network-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
network-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
network-okhttp3 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

# Room DB
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-nav" }

# Other
other-joda = { module = "joda-time:joda-time", version.ref = "joda" }
other-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

# Worker
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-hilt = { module = "androidx.hilt:hilt-work", version.ref = "work-hilt" }
androidx-work-hiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "work-hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-foundation",
    "compose-material",
]
network = [
    "network-retrofit",
    "network-gson",
    "network-mock",
    "network-okhttp3",
    "network-scalars"
]
room = [
    "room-runtime",
    "room-ktx"
]
